[package]
name = "vitte-rs"
version = "0.1.0"
authors = ["TheSirC <clocloranely@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.1"
